### ISSUE TITLE
The terrain and building information

### ISSUE THREAD

**Issue by FFFionana** [ShuhangZhang/FDRadiomap#2]
Will the remaining types of terrain and building information be released here?

**Comment by ShuhangZhang** [comment]
Thank you for your question. Due to the storage limitation, we will upload the entire dataset to Google Drive. It'll be released soon.

**Comment by FFFionana** [comment]
Could you explain the scaling relationship between the grayscale value of an image and the RSS?

**Comment by ShuhangZhang** [comment]
> Could you explain the scaling relationship between the grayscale value of an image and the RSS?

Thank you for this question. The range of the RSS is [-120dBm, 60dBm], and is uniformly divided into 256 grayscales. A lighter color corresponds to a higher RSS.

**Comment by FFFionana** [comment]
Thank you for your response, it is very helpful for me in using the dataset.
